---
# Variables specific to Docker Swarm manager nodes
swarm_manager: true

# Manager-specific Docker configurations
docker_swarm_manager_options: "--availability active"

# Stack deployment settings
stack_name: jenkinsstack
stack_file: /tmp/docker-stack.yml
