all:
  hosts:
    manager1:
      ansible_host: 34.200.234.86
    worker1:
      ansible_host: 34.200.217.88
    worker2:
      ansible_host: 35.170.80.190

  children:
    managers:
      hosts:
        manager1:
    workers:
      hosts:
        worker1:
        worker2: