all:
  hosts:
    manager1:
      ansible_host: <MANAGER_IP>
    worker1:
      ansible_host: <WORKER1_IP>
    worker2:
      ansible_host: <WORKER2_IP>

  children:
    managers:
      hosts:
        manager1:
    workers:
      hosts:
        worker1:
        worker2: