all:
  hosts:
    manager1:
      ansible_host: 54.173.107.232
    worker1:
      ansible_host: 3.227.243.134
    worker2:
      ansible_host: 44.198.170.154

  children:
    managers:
      hosts:
        manager1:
    workers:
      hosts:
        worker1:
        worker2: