name: Deploy to Swarm

on:
  push:
    branches:
      - main

jobs:
  provision-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Ansible & dependencies
        run: |
          python -m pip install ansible ansible-lint
          ansible-galaxy collection install community.docker

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible to provision swarm
        run: |
          ansible-playbook -i ansible/inventory/hosts.yml ansible/playbooks/01-provision.yml

      - name: Create Docker Swarm
        run: |
          ansible-playbook -i ansible/inventory/hosts.yml ansible/playbooks/02-docker-swarm.yml

      - name: Deploy Stack
        run: |
          ansible-playbook -i ansible/inventory/hosts.yml ansible/playbooks/03-deploy-stack.yml